# Copyright (c) 2016-2025 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Material for MkDocs
site_url: https://leafcxy.github.io/mkdocs-material/
site_author: leafcxy
site_description: >-
  用Markdown编写文档,并在
  分钟-可搜索、可定制,支持60多种语言,适用于所有设备

# Repository
repo_name: leafcxy/mkdocs-material
repo_url: https://github.com/leafcxy/mkdocs-material

# Copyright
copyright: Copyright &copy; 2016 - 2025 leafcxy

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - blog
  - search
  # - search:
  #     separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true

# # Hooks
# hooks:
#   - overrides/hooks/shortcodes.py
#   - overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leafcxy
    - icon: fontawesome/brands/telegram
      link: https://t.me/leafcxybot
      name: telegram

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree
nav:
  - 主页: index.md
  - 开始:
    - 安装: getting-started.md
    - 创建您的网站: creating-your-site.md
    - 发布您的网站: publishing-your-site.md
    - 自定义: customization.md
    - 约定: conventions.md
    - 浏览器支持: browser-support.md
    - 企业反馈: enterprise-support.md
    - 哲学: philosophy.md
    - 选择: alternatives.md
    - 许可证: license.md
    - 教程:
      - tutorials/index.md
      - "Blogs":
        - tutorials/blogs/basic.md
        - tutorials/blogs/navigation.md
        - tutorials/blogs/engage.md
      - "Social cards":
        - tutorials/social/basic.md
        - tutorials/social/custom.md
    - 修改日志:
      - changelog/index.md
      - 如何升级: upgrade.md
  - 安装:
    - setup/index.md
    - 更改颜色: setup/changing-the-colors.md
    - 更改字体: setup/changing-the-fonts.md
    - 更改语言: setup/changing-the-language.md
    - 更改徽标和图标: setup/changing-the-logo-and-icons.md
    - 确保数据隐私: setup/ensuring-data-privacy.md
    - 设置导航: setup/setting-up-navigation.md
    - 设置网站搜索: setup/setting-up-site-search.md
    - 设置站点分析: setup/setting-up-site-analytics.md
    - 设置社交卡: setup/setting-up-social-cards.md
    - 建立博客: setup/setting-up-a-blog.md
    - 设置标签: setup/setting-up-tags.md
    - 设置版本控制: setup/setting-up-versioning.md
    - 设置标题: setup/setting-up-the-header.md
    - 设置页脚: setup/setting-up-the-footer.md
    - 添加git存储库: setup/adding-a-git-repository.md
    - 添加评论系统: setup/adding-a-comment-system.md
    - 构建优化的网站: setup/building-an-optimized-site.md
    - 为离线使用而构建: setup/building-for-offline-usage.md
    - 扩展:
      - setup/extensions/index.md
      - Python Markdown: setup/extensions/python-markdown.md
      - Python Markdown扩展: setup/extensions/python-markdown-extensions.md
  - 插件:
    - plugins/index.md
    - 博客: plugins/blog.md
    - 组: plugins/group.md
    - 信息: plugins/info.md
    - 元: plugins/meta.md
    - 脱机的: plugins/offline.md
    - 优化: plugins/optimize.md
    - 隐私: plugins/privacy.md
    - 工程: plugins/projects.md
    - 搜索: plugins/search.md
    - 社会的: plugins/social.md
    - 标签: plugins/tags.md
    - 排版: plugins/typeset.md
    - 必要条件:
      - 图像处理: plugins/requirements/image-processing.md
      - 缓存: plugins/requirements/caching.md
  - 参考:
    - reference/index.md
    - 警告: reference/admonitions.md
    - 注释: reference/annotations.md
    - 按钮: reference/buttons.md
    - 代码块: reference/code-blocks.md
    - 内容选项卡: reference/content-tabs.md
    - 数据表: reference/data-tables.md
    - 图表: reference/diagrams.md
    - 脚注: reference/footnotes.md
    - 格式化: reference/formatting.md
    - 网格: reference/grids.md
    - 图标， 表情符号: reference/icons-emojis.md
    - 图像: reference/images.md
    - 列表: reference/lists.md
    - 数学: reference/math.md
    - 工具提示: reference/tooltips.md
  - 内部人士:
    - insiders/index.md
    - 为什么赞助我们: insiders/why-sponsor-us.md
    - 这对你有什么好处: insiders/benefits.md
    - 谁在赞助: insiders/our-sponsors.md
    - 赞助级别: insiders/sponsoring-tiers.md
    - 如何赞助: insiders/how-to-sponsor.md
    - 附加资料:
      - 付款和账单: insiders/payment-and-billing.md
      - 访问管理: insiders/access-management.md
      - 运行时间和取消: insiders/runtime-and-cancellation.md
      - 隐私: insiders/privacy.md
      - 许可证: insiders/license.md
      - 支持: support.md
    - 使用内部人员:
      - 开始: insiders/getting-started.md
    - 修改日志:
      - insiders/changelog/index.md
      - 如何升级: insiders/upgrade.md
  - 社区:
    - 捐助:
      - contributing/index.md
      - 报告错误: contributing/reporting-a-bug.md
      - 报告文档问题: contributing/reporting-a-docs-issue.md
      - 请求更改: contributing/requesting-a-change.md
      - 添加翻译: contributing/adding-translations.md
      - 发出pull请求: contributing/making-a-pull-request.md
      - 问问题: https://github.com/squidfunk/mkdocs-material/discussions
    - 指南:
      - 创建复制品: guides/creating-a-reproduction.md
    - 社区专家计划:
      - insiders/community-experts-program/index.md
  - 博客:
    - blog/index.md